services:
    prez.autolocktopics.acplistener:
        class: prez\autolocktopics\event\acplistener
        arguments:
            - @controller.helper
            - @user
        tags:
            - { name: event.listener }

    prez.autolocktopics.cron.task.core.auto_lock_all_forums:
        class: prez\autolocktopics\cron\task\core\auto_lock_all_forums
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @config
            - @dbal.conn
        calls:
            - [set_name, [cron.task.core.auto_lock_all_forums]]
        tags:
            - { name: cron.task }

    prez.autolocktopics.cron.task.core.auto_lock_forum:
        class: prez\autolocktopics\cron\task\core\auto_lock_forum
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @config
            - @dbal.conn
        calls:
            - [set_name, [cron.task.core.auto_lock_forum]]
        tags:
            - { name: cron.task }
